# KEYWORD: migration — a numbered database change applied in the same order everywhere the site runs.

# Generated by Django 5.2.15 on 2026-07-22 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# WHY: Records this numbered database change so every copy of the site applies it in the same order.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('provider_created_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_as_first_user', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations_as_second_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='kindlelise.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('public_place', models.CharField(max_length=200)),
                ('public_url', models.URLField(max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=9)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_details_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_approved', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=6)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_participations', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='kindlelise.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_status', models.CharField(blank=True, max_length=80, null=True)),
                ('access_until', models.DateTimeField(blank=True, null=True)),
                ('latest_provider_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('biography', models.TextField(blank=True, default='', max_length=500)),
                ('broad_area', models.CharField(blank=True, default='', max_length=20)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='kindlelise.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('misleading_plan', 'Misleading plan'), ('safety_concern', 'Safety concern'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('received', 'Received'), ('reviewed', 'Reviewed')], default='received', max_length=8)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='kindlelise.conversation')),
                ('reported_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='kindlelise.message')),
                ('reported_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='kindlelise.plan')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked_user')), _negated=True), name='block_users_differ'), models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='block_direction_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['first_user', 'updated_at'], name='conv_first_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['second_user', 'updated_at'], name='conv_second_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('first_user', models.F('second_user')), _negated=True), name='conversation_users_differ'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('first_user__lt', models.F('second_user'))), name='conversation_users_ordered'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('first_user', 'second_user'), name='conversation_pair_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='message_convo_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['status', 'starts_at'], name='plan_status_starts_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='plan_capacity_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('status', 'approved')), models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', True), ('approved_by__isnull', True)), _connector='OR'), name='plan_approval_fields_match'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['plan', 'status'], name='particip_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'status'], name='particip_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('plan', 'user'), name='participation_plan_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('left_at__isnull', True), ('status', 'joined')), models.Q(('left_at__isnull', False), ('status', 'left')), _connector='OR'), name='participation_left_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified', 'broad_area'], name='profile_verified_area_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_verified', True), ('verified_at__isnull', False), ('verified_by__isnull', False)), models.Q(('is_verified', False), ('verified_at__isnull', True), ('verified_by__isnull', True)), _connector='OR'), name='profile_verification_fields_match'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'received_at'], name='report_status_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='report_users_differ'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reported_conversation__isnull', True), ('reported_plan__isnull', True)), models.Q(('reported_message__isnull', True), ('reported_plan__isnull', True)), models.Q(('reported_conversation__isnull', True), ('reported_message__isnull', True)), _connector='OR'), name='report_at_most_one_context'),
        ),
    ]
