# Generated by Django 5.2.15 on 2026-07-27 17:23

import kindlelise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindlelise', '0003_profile_availability_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to=kindlelise.models.profile_image_upload_path),
        ),
    ]
