# KEYWORD: migration — a numbered database change applied in the same order everywhere the site runs.

# Generated by Django 5.2.15 on 2026-08-05

import kindlelise.models
from django.db import migrations, models


# WHY: Records this numbered database change so every copy of the site applies it in the same order.
class Migration(migrations.Migration):

    dependencies = [
        ("kindlelise", "0004_add_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=kindlelise.models.plan_thumbnail_upload_path,
            ),
        ),
    ]
