# Generated by Django 5.2.15 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kindlelise", "0005_add_plan_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="title_statement",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
